language: node_js
nodejs:
- stable
branches:
  only:
  - master
env:
  global:
  - REMOTE_PATH=Uploads/Travis_CI/Hello_World_Test
  - REMOTE_USER=adpcuser
  - REMOTE_HOST=165.227.131.21
  - REMOTE_PORT=6622
before_install:
- openssl aes-256-cbc -K $encrypted_b525089bd38a_key -iv $encrypted_b525089bd38a_iv
  -in deploy-travis.enc -out deploy-travis -d
- bash scripts/install.sh
after_success:
- bash scripts/deploy.sh
