language: node_js
nodejs:
<<<<<<< HEAD
  - stable
branches:
  only:
  - build_gh
after_success:
  - bash scripts/deploy.sh
deploy:
  local_dir: build_gh
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: build_gh
=======
- stable
branches:
  only:
  - master
env:
  global:
  - REMOTE_PATH=Uploads/Travis_CI/Hello_World_Test
  - REMOTE_USER=adpcuser
  - REMOTE_HOST=165.227.171.172
  - REMOTE_PORT=6622
before_install:
- bash scripts/install.sh
after_success:
- bash scripts/deploy.sh
>>>>>>> b5c55e7860509a670a36bf11804263f559636232
