language: node_js
nodejs:
- stable
env:
  global:
  - REMOTE_PATH=Uploads/Travis_CI/Hello_World_Test
  - REMOTE_USER=adpcuser
  - REMOTE_HOST=165.227.131.21
  - REMOTE_PORT=6622
before_install:
- bash scripts/install.sh
after_success:
- bash scripts/deploy.sh
