language: node_js
nodejs:
- stable
env:
  global:
  - REMOTE_PATH=${REMOTE_PATH}
  - REMOTE_USER=${REMOTE_USER}
  - REMOTE_HOST=${REMOTE_HOST}
  - REMOTE_PORT=${REMOTE_PORT}
before_install:
- bash scripts/install.sh
after_success:
- bash scripts/deploy.sh
